#!/usr/bin/env python
# coding: utf-8

# In[ ]:


numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

print("Even numbers in the list:")
for number in numbers:
    # Use modulo to check for odd numbers
    if number % 2 != 0:
        continue  # Skip to the next iteration
    print(number)

